/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: 'class',
    theme: {
        screens: {
            'xs': '480px',
            'sm': '640px',
            'md': '768px',
            'lg': '1024px',
            'xl': '1280px',
            '2xl': '1536px',
        },
        extend: {
            colors: {
                'z': {
                    'bg': 'var(--z-bg)',
                    'bg-secondary': 'var(--z-bg-secondary)',
                    'surface': 'var(--z-surface)',
                    'surface-hover': 'var(--z-surface-hover)',
                    'elevated': 'var(--z-elevated)',
                    'elevated-hover': 'var(--z-elevated-hover)',
                    'border': 'var(--z-border)',
                    'border-light': 'var(--z-border-light)',
                    'text': 'var(--z-text)',
                    'text-secondary': 'var(--z-text-secondary)',
                    'text-muted': 'var(--z-text-muted)',
                    'chip': 'var(--z-chip)',
                    'chip-active': 'var(--z-chip-active)',
                    'chip-text': 'var(--z-chip-text)',
                    'chip-text-active': 'var(--z-chip-text-active)',
                },
                'brand': {
                    DEFAULT: '#FF0000',
                    light: '#FF4E45',
                    dark: '#cc0000',
                    50: '#fff5f5',
                    100: '#ffe3e3',
                    200: '#ffc9c9',
                    300: '#ffa8a8',
                    400: '#ff6b6b',
                    500: '#FF0000',
                    600: '#cc0000',
                    700: '#a30000',
                    800: '#7a0000',
                    900: '#520000',
                },
                'accent': {
                    blue: '#065fd4',
                    'blue-light': '#3ea6ff',
                    cyan: '#06b6d4',
                    gold: '#f59e0b',
                    'gold-light': '#fbbf24',
                    rose: '#ff0000',
                    emerald: '#10b981',
                    orange: '#f97316',
                },
            },
            fontFamily: {
                sans: ['Roboto', 'Arial', 'sans-serif'],
            },
            backgroundImage: {
                'gradient-brand': 'linear-gradient(135deg, #FF0000 0%, #cc0000 100%)',
                'gradient-surface': 'linear-gradient(180deg, var(--z-surface) 0%, var(--z-bg) 100%)',
            },
            animation: {
                'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'slide-up': 'slideUp 0.2s ease-out',
                'slide-down': 'slideDown 0.2s ease-out',
                'slide-in-right': 'slideInRight 0.25s ease-out',
                'fade-in': 'fadeIn 0.15s ease-out',
                'scale-in': 'scaleIn 0.15s ease-out',
                'scale-up': 'scaleUp 0.2s ease-out',
                'shimmer': 'shimmer 1.5s linear infinite',
                'spin-slow': 'spin 3s linear infinite',
            },
            keyframes: {
                slideUp: {
                    '0%': { transform: 'translateY(8px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                slideDown: {
                    '0%': { transform: 'translateY(-8px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                slideInRight: {
                    '0%': { transform: 'translateX(16px)', opacity: '0' },
                    '100%': { transform: 'translateX(0)', opacity: '1' },
                },
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                scaleIn: {
                    '0%': { transform: 'scale(0.95)', opacity: '0' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                scaleUp: {
                    '0%': { transform: 'scale(0.9)', opacity: '0' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                shimmer: {
                    '0%': { backgroundPosition: '-200% 0' },
                    '100%': { backgroundPosition: '200% 0' },
                },
            },
            boxShadow: {
                'glow': '0 0 10px rgba(255, 0, 0, 0.15)',
                'glow-lg': '0 0 20px rgba(255, 0, 0, 0.25)',
                'premium': 'var(--z-premium-shadow)',
                'card': 'var(--z-card-shadow)',
                'elevated': 'var(--z-elevated-shadow)',
            },
            borderRadius: {
                'xl': '12px',
                '2xl': '16px',
                '3xl': '24px',
            },
        },
    },
    plugins: [],
}
